In [3]:
pip install wooldridge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
import numpy as np
import pandas as pd
import wooldridge as wd

In [17]:
wage = wd.data('wage1')[['wage','educ','exper']]
wage

wage  educ  exper
0     3.10    11      2
1     3.24    12     22
2     3.00    11      2
3     6.00     8     44
4     5.30    12      7
..     ...   ...    ...
521  15.00    16     14
522   2.27    10      2
523   4.67    15     13
524  11.56    16      5
525   3.50    14      5

[526 rows x 3 columns]

In [25]:
y=wage['wage'].to_numpy()
x=wage[['educ','exper']].to_numpy()
u = wage.to_numpy()

In [26]:
x.T

array([[11, 12, 11, ..., 15, 16, 14],
       [ 2, 22,  2, ..., 13,  5,  5]])

In [27]:
np.linalg.inv(x.T.dot(x))

array([[ 2.41194181e-05, -1.03187955e-05],
       [-1.03187955e-05,  8.43022706e-06]])

In [28]:
betas=np.linalg.inv(x.T.dot(x)).dot(x.T.dot(y))
betas

array([0.41704634, 0.04543817])

In [29]:
u

array([[ 3.0999999 , 11.        ,  2.        ],
       [ 3.24000001, 12.        , 22.        ],
       [ 3.        , 11.        ,  2.        ],
       ...,
       [ 4.67000008, 15.        , 13.        ],
       [11.56000042, 16.        ,  5.        ],
       [ 3.5       , 14.        ,  5.        ]])

In [32]:
x.dot(betas)

array([4.67838605, 6.00419572, 4.67838605, 5.33565003, 5.32262322,
       7.0816849 , 8.18840658, 5.23174689, 6.18594838, 8.08942741,
       7.03624674, 5.55791689, 5.68612855, 5.82244305, 6.41313922,
       7.30887574, 5.45893772, 6.14861306, 5.59525222, 6.64033005,
       5.50437589, 6.32226288, 7.0816849 , 5.14087055, 6.26872188,
       6.80905591, 7.17256124, 8.08132457, 7.61884006, 3.7453142 ,
       6.88372656, 5.92952506, 6.14861306, 5.32262322, 5.14087055,
       7.67238107, 5.68612855, 3.44027385, 5.97496323, 5.50437589,
       5.14087055, 5.91331939, 6.56565939, 6.63222721, 5.92142222,
       7.1644584 , 4.21590155, 6.64033005, 6.24759223, 5.68612855,
       5.82244305, 6.80905591, 5.68612855, 5.32262322, 5.09543239,
       6.39200957, 6.71817957, 3.92706687, 7.87033941, 6.99080857,
       7.23912905, 7.74705173, 5.80623737, 4.76115954, 6.24759223,
       7.02004106, 6.99080857, 6.14051022, 7.12712307, 5.14087055,
       6.80905591, 7.86223658, 5.77700489, 5.91331939, 5.32262

In [33]:
y_est=x.dot(betas)

In [34]:
y-y_est

array([-1.57838614e+00, -2.76419571e+00, -1.67838605e+00,  6.64349968e-01,
       -2.26230294e-02,  1.66831510e+00,  3.06159342e+00, -2.31746887e-01,
       -2.58594848e+00,  1.00905729e+01, -7.86246738e-01,  2.57208322e+00,
        3.08387191e+00, -3.22443052e-01,  1.57868615e+01,  1.00211242e+01,
        2.04106228e+00,  4.48138706e+00, -1.99525231e+00, -2.14033005e+00,
        1.37562423e+00,  2.15773666e+00, -7.51684981e-01, -4.61087058e+00,
       -2.68721879e-01,  2.75094451e+00,  6.07438972e-01,  4.41867543e+00,
        4.88115994e+00, -4.95314202e-01,  6.11627344e+00, -1.42952506e+00,
        3.53138725e+00, -3.22623220e-01, -4.60870726e-01, -3.40238109e+00,
        4.63871543e-01,  6.97261429e-02, -2.97496323e+00,  7.45624114e-01,
        2.66912939e+00,  4.08668061e+00, -2.06565939e+00, -2.63222721e+00,
        4.58577890e-01,  6.53554141e+00, -2.54590159e+00, -3.71032998e+00,
       -2.59759213e+00, -2.78612846e+00, -4.19244306e+00,  1.79094448e+00,
       -6.86128553e-01,  

In [35]:
u_est=y-y_est

In [39]:
y.shape #número de datos totales

(526,)

In [41]:
sum(u_est**2)

5755.692073126875

In [43]:
n,k=x.shape
n,k

(526, 2)

In [50]:
sigma=sum(u_est**2)/(n-k)
sigma

10.984145177723043

In [51]:
x.T

array([[11, 12, 11, ..., 15, 16, 14],
       [ 2, 22,  2, ..., 13,  5,  5]])

In [52]:
x.T.dot(x)

array([[ 87040, 106539],
       [106539, 249027]])

In [56]:
Error_est=np.diag(np.sqrt(np.linalg.inv(x.T.dot(x))*sigma))
Error_est

<ipython-input-56-3fb2c2e9d038>:1: RuntimeWarning: invalid value encountered in sqrt
  Error_est=np.diag(np.sqrt(np.linalg.inv(x.T.dot(x))*sigma))


array([0.01627671, 0.00962283])

In [59]:
t= betas/Error_est
t

array([25.62227963,  4.72191354])

In [62]:
int_confianza_sup= betas+1.96*(Error_est)
int_confianza_sup

array([0.44894868, 0.06429891])

In [65]:
int_confianza_inf= betas-1.96*(Error_est)
int_confianza_inf

array([0.38514399, 0.02657742])

In [ ]:
# Los dos intervalos de confianza son estadísticamente significativos